tests: use Gnulib's init.sh test framework
This simplifies the tests since, among other things, we no longer have
to manage temporary files ourselves, since the init.sh file manages that
for us. It also serves as a good example since many GNU packages use
this script.

* NEWS: Mention the improvement.
* bootstrap.conf (bootstrap_post_import_hook): Copy tests/init.sh from
Gnulib.
* Makefile.am (EXTRA_DIST): Add the file imported from Gnulib.
* .gitignore: Likewise.
* cfg.mk (VERBOSE): New variable.
* tests/atexit-1: Use the new file.
* tests/greeting-1: Likewise.
* tests/hello-1: Likewise.
* tests/last-1: Likewise.
* tests/operand-1: Likewise.
* tests/traditional-1: Likewise.
* tests/greeting-2: Likewise. Reword a comment.

diff --git a/tests/atexit-1 b/tests/atexit-1
--- a/tests/atexit-1
+++ b/tests/atexit-1
@@ -7,25 +7,13 @@
 # are permitted in any medium without royalty provided the copyright
 # notice and this notice are preserved.
 
-trap 'rm -fr $tmpfiles' 1 2 3 15
+. "${srcdir=.}/tests/init.sh"; path_prepend_ .
 
-if ! [ -c /dev/full ]; then
-  # no such character device, skip this check
-  exit 77
+if ! test -w /dev/full || ! test -c /dev/full; then
+  skip_ '/dev/full is required'
 fi
 
-tmpfiles="$tmpfiles atexit-test1.out"
-: ${HELLO=hello}
-${HELLO} 2>&1 1>/dev/full | tr -d '\r' >atexit-test1.out
+returns_ 1 hello >/dev/full 2>err || fail=1
+grep "^hello: write error" err || fail=1
 
-# remove \r (CR) characters from the output, so that the tests work on
-# platforms with CRLF line endings.  There is apparently no reliable
-# method (across Cygwin, MingW, etc.) to force an eol style.
-
-: ${GREP=grep}
-${GREP} "^hello: write error" atexit-test1.out
-result=$?
-
-rm -fr $tmpfiles
-
-exit $result
+Exit $fail
